# Generated by Django 4.2.2 on 2023-06-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSubBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='subblog',
            name='image',
        ),
        migrations.AddField(
            model_name='subblog',
            name='title',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='imagesubblog',
            name='subblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subblog'),
        ),
    ]
