# Generated by Django 4.2.2 on 2023-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagesubblog_remove_subblog_image_subblog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesubblog',
            name='is_wide',
            field=models.BooleanField(default=False),
        ),
    ]
