# Generated by Django 4.2.2 on 2023-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_travel_blog_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='modified_date',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
