# Generated by Django 4.2.2 on 2023-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='day',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
